[dependencies]
bitflags = "1.3.2"

[dependencies.bevy]
workspace = true

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "dissolve-sphere-standard-material-extension"
version = "0.1.0"
