[package]
edition = "2021"
name = "dissolve-sphere-standard-material-extension"
version = "0.1.0"

[dependencies]
bitflags = "1.3.2"
bevy = { workspace = true }
bevy_shader_utils = { workspace = true }
bevy_prepass_debug = { workspace = true }
