license = "MIT OR Apache-2.0"

[workspace]
members = [
  # "examples/*",
  # "examples/candy-cane",
  # "examples/cartoon-water",
  # "examples/compute-3d",
  # "examples/compute-with-time",
  "examples/cube-wave",
  "examples/dissolve-sphere-standard-material-extensions",
  # "examples/fresnel-effect",
  # "examples/infinite-tunnel",
  # "examples/pointcloud",
  # "examples/pressure-wave-sphere",
  # "examples/rotating-column",
  # "examples/shader-rgb-worldspace-cube",
  "examples/shader-test-001",
  # "examples/shield-spheres",
  "examples/shield-with-depth",
  # "examples/spacecraft-noiseland",
  # "examples/standard-material-quixel-megascan",
  "libs/*",
  # "vendor/bevy_asset_loader/bevy_asset_loader_derive",
  # "vendor/bevy_asset_loader/bevy_asset_loader",
  # , "vendor/bevy/crates/*"
]

resolver = "2"
# # Enable a small amount of optimization in debug mode
# [profile.dev]
# opt-level = 1

# # Enable high optimizations for dependencies (incl. Bevy), but not for our code:
# [profile.dev.package."*"]
# opt-level = 3


[workspace.dependencies]
# bevy = { git = "https://github.com/christopherbiscardi/bevy", branch ="vertex-colors-prepass" }
bevy = { git = "https://github.com/bevyengine/bevy", features = [
  "jpeg",
  "file_watcher",
] }
## use random PR fork of egui for 0.12
bevy-inspector-egui = { git = "https://github.com/raffaeleragni/bevy-inspector-egui", branch = "bevy_0_12" }
# bevy-inspector-egui = "0.20.0"
bevy_asset_loader = { git = "https://github.com/NiklasEi/bevy_asset_loader", branch = "bevy_main" }
bevy_tweening = { git = "https://github.com/djeedai/bevy_tweening" }
bevy_basic_camera = { path = "./libs/bevy_basic_camera" }
bevy_shader_utils = { path = "./libs/bevy_shader_utils" }
bevy_prepass_debug = { path = "./libs/bevy_prepass_debug" }

[patch."https://github.com/bevyengine/bevy"]
bevy = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass", features = [
  "jpeg",
] }

bevy_app = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_asset = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_core = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_ecs = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_hierarchy = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_log = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_math = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_reflect = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_utils = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_window = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }

bevy_core_pipeline = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_pbr = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }
bevy_render = { git = "https://github.com/christopherbiscardi/bevy", branch = "vertex-colors-prepass" }

# [patch.crates-io]
# bevy = { git = "https://github.com/christopherbiscardi/bevy", branch ="vertex-colors-prepass" }
