license = "MIT OR Apache-2.0"

[workspace]
members = [
  # "examples/*",
  # "examples/candy-cane",
  # "examples/cartoon-water",
  # "examples/compute-3d",
  "examples/compute-with-time",
  "examples/cube-wave",
  "examples/dissolve-sphere-standard-material-extensions",
  # "examples/fresnel-effect",
  # "examples/infinite-tunnel",
  # "examples/pointcloud",
  # "examples/pressure-wave-sphere",
  # "examples/rotating-column",
  # "examples/shader-rgb-worldspace-cube",
  "examples/shader-test-001",
  # "examples/shield-spheres",
  "examples/shield-with-depth",
  # "examples/spacecraft-noiseland",
  # "examples/standard-material-quixel-megascan",
  "examples/ui-button-shader",
  "libs/*",
  # "vendor/bevy_asset_loader/bevy_asset_loader_derive",
  # "vendor/bevy_asset_loader/bevy_asset_loader",
  # , "vendor/bevy/crates/*"
]

resolver = "2"
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.12", features = ["jpeg", "file_watcher"] }
bevy-inspector-egui = "0.21"
bevy_asset_loader = "0.19.1"
bevy_tweening = "0.9.0"
bevy_basic_camera = { path = "./libs/bevy_basic_camera" }
bevy_shader_utils = { path = "./libs/bevy_shader_utils" }
bevy_prepass_debug = { path = "./libs/bevy_prepass_debug" }

# [patch."https://github.com/bevyengine/bevy"]
# bevy = "0.12"

# bevy_app = { git = "https://github.com/bevyengine/bevy" }
# bevy_asset = { git = "https://github.com/bevyengine/bevy" }
# bevy_core = { git = "https://github.com/bevyengine/bevy" }
# bevy_ecs = { git = "https://github.com/bevyengine/bevy" }
# bevy_hierarchy = { git = "https://github.com/bevyengine/bevy" }
# bevy_log = { git = "https://github.com/bevyengine/bevy" }
# bevy_math = { git = "https://github.com/bevyengine/bevy" }
# bevy_reflect = { git = "https://github.com/bevyengine/bevy" }
# bevy_utils = { git = "https://github.com/bevyengine/bevy" }
# bevy_window = { git = "https://github.com/bevyengine/bevy" }

# bevy_core_pipeline = { git = "https://github.com/bevyengine/bevy" }
# bevy_pbr = { git = "https://github.com/bevyengine/bevy" }
# bevy_render = { git = "https://github.com/bevyengine/bevy" }

# [patch.crates-io]
# bevy = { git = "https://github.com/bevyengine/bevy", branch ="vertex-colors-prepass" }
