license = "MIT OR Apache-2.0"

[workspace]
members = [
  # "examples/*",
  # "examples/candy-cane",
  # "examples/cartoon-water",
  # "examples/compute-3d",
  # "examples/cube-wave",
  # "examples/dissolve-sphere-standard-material-extensions", "examples/eight-way-sprites",
  # --  "examples/fresnel-effect",
  # "examples/infinite-tunnel",
  # "examples/pointcloud",
  # "examples/pressure-wave-sphere",
  # "examples/rotating-column",
  # "examples/shader-rgb-worldspace-cube",
  # "examples/shader-test-001",
  # "examples/shield-spheres",
  # "examples/shield-with-depth", "examples/start-menu-hades",
  # "examples/spacecraft-noiseland",
  # "examples/ui-button-shader",
  #--  # "examples/raymarch-sphere",
  "libs/*",
  # "vendor/bevy_asset_loader/bevy_asset_loader_derive",
  # "vendor/bevy_asset_loader/bevy_asset_loader",
  # , "vendor/bevy/crates/*"
]
exclude = ["examples/compute-with-time"]

resolver = "2"

[workspace.lints.clippy]
type_complexity = "allow"
too_many_arguments = "allow"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[workspace.dependencies]
bevy = { version = "0.15.0-dev", features = ["jpeg", "file_watcher"] }
# bevy-inspector-egui = "0.25"
# bevy_asset_loader = "0.21"
# bevy_tweening = "0.11.0"
# bevy_panorbit_camera = "0.19"
# bevy_basic_camera = { path = "./libs/bevy_basic_camera" }
bevy_shader_utils = { path = "./libs/bevy_shader_utils" }
bevy_prepass_debug = { path = "./libs/bevy_prepass_debug" }

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy" }
