license = "MIT OR Apache-2.0"

[workspace]
members = [
    "examples/*",
    "libs/*",
    # "vendor/bevy_asset_loader/bevy_asset_loader_derive",
    # "vendor/bevy_asset_loader/bevy_asset_loader",
    # , "vendor/bevy/crates/*"
]

resolver = "2"
