[package]
name = "bloom-2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_rapier2d = "0.19.0"

[dependencies.bevy]
workspace = true
