[dependencies.bevy]
workspace = true

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[lints]
workspace = true

[package]
edition = "2021"
name = "shader-rgb-worldspace-cube"
version = "0.1.0"
