
[dependencies]
itertools = "0.13.0"
bevy_asset_loader.workspace = true
[dependencies.bevy]
workspace = true
features = ["jpeg"]

[lints]
workspace = true

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "shield-spheres"
version = "0.1.0"
