
[dependencies]
itertools = "0.10.3"
bevy_asset_loader = "0.15.0"
[dependencies.bevy]
workspace = true
features = ["jpeg"]

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "shield-spheres"
version = "0.1.0"
