[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "pressure-wave-sphere"
version = "0.1.0"

[lints]
workspace = true

[dependencies.bevy]
workspace = true
