[dependencies]
bitflags = "1.3.2"

[dependencies.bevy]
workspace = true
features = ["jpeg"]

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "candy-cane"
version = "0.1.0"
