[dependencies]
itertools = "0.10.3"
noise = "0.7.0"

[dependencies.bevy]
version = "0.8"

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "spacecraft-noiseland"
version = "0.1.0"
