[package]
edition = "2021"
name = "spacecraft-noiseland"
version = "0.1.0"

[dependencies]
noise = "0.7.0"

[lints]
workspace = true

[dependencies.bevy]
workspace = true

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"
