[dependencies.bevy]
workspace = true
features = ["jpeg"]

[dependencies.bevy_shader_utils]
path = "../../libs/bevy_shader_utils"

[package]
edition = "2021"
name = "standard-material-quixel-megascan"
version = "0.1.0"
